
- name: Install Zabbix Agent Zimbra template
  hosts: zmx
  become: yes

  tasks:
   - name: Delete old zabbix-agent configure
     file:
      path: /etc/zabbix/zabbix_agentd.d/yo-zimbra.conf
      state: absent

   - name: Delete old sudoers configure
     file:
      path: /etc/sudoers.d/03_zabbix
      state: absent

   - name: Copy module mon_zimbra.conf
     copy:
       src: /etc/ansible/zabbix/files/zabbix/mon_zimbra.conf
       dest: /etc/zabbix/zabbix_agentd.d/

   - name: Copy sudo_zabbix_agent.conf
     copy:
       src: /etc/ansible/zabbix/files/zabbix/sudo_zabbix_agent
       dest: /etc/sudoers.d/

   - name: zimbra_services.sh
     copy:
       src: /etc/ansible/zabbix/files/zabbix/zimbra_services.sh
       dest: /etc/zabbix/scripts/

   - name: zimbra_version.sh
     copy:
       src: /etc/ansible/zabbix/files/zabbix/zimbra_version.sh
       dest: /etc/zabbix/scripts/

   - name: Change file permissions of zimbra_service.sh
     file:
      path: /etc/zabbix/scripts/zimbra_services.sh
      mode: "+x"

   - name: Change file permissions of zimbra_version.sh
     file:
      path: /etc/zabbix/scripts/zimbra_version.sh
      mode: "+x"

   - name: Restart Zabbix Agent
     notify:
      - Restart Zabbix Agent service


  handlers:
   - name: Restart Zabbix Agent service
     service:
       name: zabbix-agent
       state: restarted

